### ISSUE TITLE
Use vscode variables

### ISSUE THREAD

**Issue by pilotak** [janjongboom/mbed-vscode-generator#9]
Great advantage of vscode is that it supports variables you don't need to include absolute path - code will then become more portable you share it with somebody else and has a project saved elsewhere.

`programName` would become `${workspaceRootFolderName}`
https://github.com/janjongboom/mbed-vscode-generator/blob/8f6dae986854da00e90d98dabf75798d14b4f4b2/cli.js#L342

`program.inputDir` would become `${workspaceRoot}`
https://github.com/janjongboom/mbed-vscode-generator/blob/8f6dae986854da00e90d98dabf75798d14b4f4b2/cli.js#L39

**Comment by janjongboom** [comment]
I've opted against this because I personally have run into many issues with paths not properly being set up in the C++ plugin and absolute paths always work. I wouldn't recommend sharing your .vscode folder with others. E.g. GCC MIDebuggerPath path will be absolute as well (vscode doesn't support searching the path for those) so it's not portable anyway.

**Comment by pilotak** [comment]
ok
